// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCZ0YyLd_ds0r9JMOr6A61v1AZfpv_DJE',
    appId: '1:646212787138:web:3a0027f4e295daa39f545b',
    messagingSenderId: '646212787138',
    projectId: 'chaty-31f13',
    authDomain: 'chaty-31f13.firebaseapp.com',
    storageBucket: 'chaty-31f13.appspot.com',
    measurementId: 'G-J4HNMP0349',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv2Fd0ygVNQYr_PP_7mLa4SrDF202NPRI',
    appId: '1:646212787138:android:f55ad9f3538857a29f545b',
    messagingSenderId: '646212787138',
    projectId: 'chaty-31f13',
    storageBucket: 'chaty-31f13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLmBo1IauOpUnRFDKJsmYTWYL2b7_n1zw',
    appId: '1:646212787138:ios:3df47427cee77a6f9f545b',
    messagingSenderId: '646212787138',
    projectId: 'chaty-31f13',
    storageBucket: 'chaty-31f13.appspot.com',
    iosBundleId: 'com.example.chatyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLmBo1IauOpUnRFDKJsmYTWYL2b7_n1zw',
    appId: '1:646212787138:ios:3df47427cee77a6f9f545b',
    messagingSenderId: '646212787138',
    projectId: 'chaty-31f13',
    storageBucket: 'chaty-31f13.appspot.com',
    iosBundleId: 'com.example.chatyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCZ0YyLd_ds0r9JMOr6A61v1AZfpv_DJE',
    appId: '1:646212787138:web:79b232aae42790e59f545b',
    messagingSenderId: '646212787138',
    projectId: 'chaty-31f13',
    authDomain: 'chaty-31f13.firebaseapp.com',
    storageBucket: 'chaty-31f13.appspot.com',
    measurementId: 'G-1DJMT7V6R5',
  );

}